feat(dns): dns managed zone and dns record
livelink/terraform-google-justintime pull request #1
Opened 2023-08-02 16:01 UTC by bethdevopsbunny

2023-08-02 18:57 UTC, Tensho commented on dns.tf
> +  ttl  = 300
I guess 24 hours is OK for us 👌 We always can downscale it to 1 min if there will be a need to re-create Cloud Run deployment. Remember, we pay for each DNS request in the cloud.
```suggestion
  ttl  = 86400
```

2023-08-02 18:57 UTC, Tensho approved these changes

2023-08-04 03:40 UTC, new-light-106 commented
Blockchainlog.in

2023-08-04 03:46 UTC, new-light-106 requested changes
Blockchainlog.in

2023-08-04 03:46 UTC, new-light-106 commented on dns.tf
> +  dns_name    = "${var.dns_name}."
Blockchainlog.in

2023-08-04 03:46 UTC, new-light-106 commented on dns.tf
> +  dns_name    = "${var.dns_name}."
Blockchainlog.in

2023-08-04 10:48 UTC, merged